#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

cp "$DIR/server/GraphicsSettingsDX9.ini" "$DIR/games/async-1/GraphicsSettingsDX9.ini"
cp "$DIR/server/UserSettings.ini" 	 "$DIR/games/async-1/UserSettings.ini"
cp "$DIR/server/config.ini" 	         "$DIR/games/async-1/config.ini"
cp "$DIR/server/GraphicsSettingsDX9.ini" "$DIR/games/async-2/GraphicsSettingsDX9.ini"
cp "$DIR/server/UserSettings.ini" 	 "$DIR/games/async-2/UserSettings.ini"
cp "$DIR/server/config.ini" 	         "$DIR/games/async-2/config.ini"
cp "$DIR/server/GraphicsSettingsDX9.ini" "$DIR/games/async-3/GraphicsSettingsDX9.ini"
cp "$DIR/server/UserSettings.ini" 	 "$DIR/games/async-3/UserSettings.ini"
cp "$DIR/server/config.ini" 	         "$DIR/games/async-3/config.ini"


docker build -t civ5server "$DIR/server"
